apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespaces.app }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.db.credentials.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.credentials.password | quote }}
  POSTGRES_DB: {{ .Values.db.credentials.database | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespaces.app }}
spec:
  clusterIP: None
  selector:
    app: db
  ports:
    - name: postgres
      port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: {{ .Values.namespaces.app }}
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.db.image }}
          ports:
            - containerPort: {{ .Values.db.port }}
              name: postgres
          resources:
            {{- toYaml .Values.db.resources | nindent 12 }}
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.db.storage }}
