apiVersion: v1
kind: ServiceAccount
metadata:
  name: segton
  namespace: cicloud
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: segton
  namespace: cicloud
rules:
  - apiGroups: ["segton.sap.com"]
    resources: ["segtonpipelineruns"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: segton
  namespace: cicloud
subjects:
  - kind: ServiceAccount
    name: segton
    namespace: cicloud
roleRef:
  kind: Role
  name: segton
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: segton
  namespace: cicloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: segton
  template:
    metadata:
      labels:
        app: segton
    spec:
      serviceAccountName: segton
      containers:
        - name: segton
          image: personalcicloud/segton:local
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              value: cicloud
            - name: PIPELINE_NAME
              value: spring-pipeline
